# Generated by Django 3.2.4 on 2021-07-01 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_todo_deadline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='deadline',
        ),
        migrations.AlterField(
            model_name='todo',
            name='work_status',
            field=models.CharField(choices=[('todo', 'todo'), ('done', 'done')], default='todo', max_length=5),
        ),
    ]
